create table if not exists public."Constellation" (
  "id" integer generated by default as identity primary key,
  "key" text not null,
  "iau" text not null,
  "name" text not null,
  "symbol" text not null,
  "dates" text not null,
  "accent" text not null,
  "note" text not null,
  "brightestStarName" text not null,
  "brightestStarSubtitle" text,
  "brightestStarSummary" text,
  "brightestStarImageUrl" text,
  "centerRa" double precision not null,
  "centerDec" double precision not null,
  "starHipIdsJson" text not null,
  "edgeHipPairsJson" text not null,
  "updatedAt" timestamptz not null default now()
);

create unique index if not exists "Constellation_key_key"
  on public."Constellation" ("key");

create unique index if not exists "Constellation_iau_key"
  on public."Constellation" ("iau");

create table if not exists public."Star" (
  "hipId" integer primary key,
  "name" text,
  "ra" double precision not null,
  "dec" double precision not null,
  "magnitude" double precision not null,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public."FeaturedStar" (
  "id" integer generated by default as identity primary key,
  "name" text not null,
  "wikiTitle" text,
  "constellation" text not null,
  "zodiacSignKey" text,
  "color" text not null,
  "priority" integer not null,
  "ra" double precision not null,
  "dec" double precision not null,
  "fact" text not null,
  "imageUrl" text,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create unique index if not exists "FeaturedStar_name_key"
  on public."FeaturedStar" ("name");

create table if not exists public."SyncState" (
  "key" text primary key,
  "checksum" text,
  "updatedAt" timestamptz not null default now()
);
